<?php

return [
    // token加密的key和iv
    'aes_key' => 'cvJwBfr2g5333bBh',
    'aes_iv' => 'abC9R123CeUaeOER',
    'req_aes_key'=>'i9hys6gdb5stfzge',
    'req_aes_iv'=>'i9hys6gdb5stfzge',
    'register_key'=>'zgxcfzjjh007!',

    'payment_conf' => [
        'key' => 'GIhthdG3yPhNvWWa8VzhLXCPEiNMCiG6',
        'pay_memberid' => '231297029',
        'pay_notifyurl' => env('app.host').'/common/paynotify',
        'pay_callbackurl' => env('common.callback_url').'/tradeSuccess',
        'payment_url' => 'https://hy543.top/Pay',
        'query_url' => 'https://hy543.top/Query',
    ],

    'payment_conf2' => [
        'key' => 'jashduwqd76738dd',
        'account_id' => 'akjsdhuw636hn',
        'pay_notifyurl' => env('app.host').'/common/paynotify2',
        'pay_callbackurl' => env('common.callback_url').'/tradeSuccess',
        'payment_url' => 'https://darlie-payment.ziwei.com.my/api/pay',
        'query_url' => 'https://hongtai01.top/Query',
    ],

    // 'payment_conf3' => [
    //     'key' => 'p4c92j9ad8egxhdsgoopkwblg9vxurty',
    //     'pay_memberid' => '230503942',
    //     'pay_notifyurl' => env('app.host').'/common/payNotify3',
    //     'pay_callbackurl' => env('common.callback_url').'/tradeSuccess',
    //     'payment_url' => 'http://tue.pikaqiukeji.top/Pay_Index.html',
    //     'query_url' => 'http://tue.pikaqiukeji.top/Pay_Trade_query.html',
    // ],

    'payment_conf3' => [
        'key' => 'zmLgTjGlAhjXpyMx7qkK6F1Es2LnkY0Q',
        'pay_memberid'=>'240196369',
        'pay_notifyurl' => env('app.host').'/common/paynotify3',
        'pay_callbackurl' => env('common.callback_url').'/tradeSuccess',
        'payment_url' => 'https://hongtai01.top/Pay',
        'query_url' => 'https://hongtai01.top/Query',
    ],
    'payment_conf4' => [
        'key' => 'kysAde26exUUCy8MDgXjRdt',
        'pay_memberid'=>'100226',
        'pay_notifyurl' => env('app.host').'/common/paynotify4',
        'pay_callbackurl' => env('common.callback_url').'/tradeSuccess',
        'payment_url' => 'https://tsapi-baoxue.tszfbb.com/api/v1/payment/init',
        'query_url' => 'https://tsapi-baoxue.tszfbb.com/api/v1/payment/query',
    ],
    'payment_conf5' => [
        'key' => 'dE0uJ1dQ6iS8bR0a',
        'pay_memberid'=>'10942',
        'pay_notifyurl' => env('app.host').'/common/paynotify5',
        'pay_callbackurl' => env('common.callback_url').'/tradeSuccess',
        'payment_url' => 'https://facaiya.vip/pay/json',
        'query_url' => 'https://hongtai01.top/Query',
    ],
    'payment_conf6' => [
        'key' => 'BKSYQGCIKIMYUUAY5SZJ7NIKDNLOHZNKNBKVIF6JBKTBZOH4BIRSH7TH7KLRE8EULB1AZXZRYXRSPO3NBVTR3IY6QVHXD5YLXMCDH6AER68GLO0ZFBJFTR1GVV3NYTSE',
        'pay_memberid'=>'20000343',
        'pay_notifyurl' => env('app.host').'/common/paynotify6',
        'pay_callbackurl' => env('common.callback_url').'/tradeSuccess',
        'payment_url' => 'http://akago.xyz:3020/api/pay/create_order',
        'query_url' => 'http://akago.xyz:3020/api/pay/query_order',
    ],
    'payment_conf7' => [
        'key' => 'IULOPQKIQT6PYGTYVK5ZGAQPJOQCSIEIQZCZE0VLWBRYLB92IR9HYBUCKFOPMWKRCRBGEKCZMQ89KOFLJYC8YTNSWFCU0HHHPELDKC663CTMEBYRUUNIYYLJHR94FIJD',
        'pay_memberid'=>'20000508',
        'pay_notifyurl' => env('app.host').'/common/paynotify7',
        'pay_callbackurl' => env('common.callback_url').'/tradeSuccess',
        'payment_url' => 'https://dfew.fxrcn.lol/api/pay/create_order',
        'query_url' => 'https://dfew.fxrcn.lol/api/pay/query_order',
    ],
    'payment_conf8' => [
        'key' => '9079DCAEF4C877',
        'pay_memberid'=>'10180',
        'pay_notifyurl' => env('app.host').'/common/paynotify8',
        'pay_callbackurl' => env('common.callback_url').'/tradeSuccess',
        'payment_url' => 'http://8.210.18.24:405/gateway/index/checkpoint',
        'query_url' => 'http://8.210.18.24:405/gateway/index/queryorder',
    ],
    'payment_conf9' => [
        'key' => '787ea64501054d039e28139f8ad4784a',
        'pay_memberid'=>'102232',
        'pay_notifyurl' => env('app.host').'/common/paynotify9',
        'pay_callbackurl' => env('common.callback_url').'/tradeSuccess',
        'payment_url' => 'http://43.198.97.242:29110/mobile/order/created',
        'query_url' => 'http://43.198.97.242:29110/mobile/order/query',
    ],
    'payment_conf10' => [
        'key' => 'kgm3tn4up2itiih4kbmaeig54erv3aax',
        'pay_memberid'=>'231188968',
        'pay_notifyurl' => env('app.host').'/common/paynotify10',
        'pay_callbackurl' => env('common.callback_url').'/tradeSuccess',
        'payment_url' => 'http://66paytue.meisuobudamiya.com/Pay_Index.html',
        'query_url' => 'http://66paytue.meisuobudamiya.com/Pay_Trade_query.html',
    ],
    'payment_conf11' => [
        'key' => '87e7324de2690b1e4d1f50e0d11adff4',
        'pay_memberid'=>'10005',
        'pay_notifyurl' => env('app.host').'/common/paynotify11',
        'pay_callbackurl' => env('common.callback_url').'/tradeSuccess',
        'payment_url' => 'http://acrossthesea.champion999.one/api/newOrder',
        'query_url' => 'http://acrossthesea.champion999.one/api/queryOrder',
    ],
    'payment_conf12' => [
        'key' => 'F048902396CC89',
        'pay_memberid'=>'10115',
        'pay_notifyurl' => env('app.host').'/common/paynotify12',
        'pay_callbackurl' => env('common.callback_url').'/tradeSuccess',
        'payment_url' => 'http://8.210.157.79:405/gateway/index/checkpoint',
        'query_url' => 'http://8.210.157.79:405/gateway/index/queryorder',
    ],
    'payment_conf13' => [
        'key' => '4A58EYR38R6XG7RV9CZTR1L1HR1GSGVBM87RTPMFFKSZK49IR14QFTTOCCKUSIEYZBQ93Y866M8UG45I9BTOJSHLCBQ4435QNXHXVE9JJAYU6K25O1WDYSIWR3WJUVUB',
        'pay_memberid'=>'20000029',
        'pay_notifyurl' => env('app.host').'/common/paynotify13',
        'pay_callbackurl' => env('common.callback_url').'/tradeSuccess',
        'payment_url' => 'https://fzf.app/api/pay/create_order',
        'query_url' => 'https://fzf.app/api/pay/query_order',
    ],
    'payment_conf_daxiang' => [
        'key' => '5d30e603c30397dbda999f9d4a8188d0',
        'pay_memberid'=>'10011',
        'pay_notifyurl' => env('app.host').'/common/payNotify_daxiang',
        'pay_callbackurl' => env('common.callback_url').'/tradeSuccess',
        'payment_url' => 'http://acrossthesea.champion999.one/api/newOrder',
        'query_url' => 'http://acrossthesea.champion999.one/api/queryOrder',
    ],
    'payment_conf_xinglian' => [
        'key' => 'kysjxKGo3uT81k88Iq2z4JB',
        'pay_memberid'=>'114',
        'pay_notifyurl' => env('app.host').'/common/payNotify_xinglian',
        'pay_callbackurl' => env('common.callback_url').'/tradeSuccess',
        'payment_url' => 'https://xinglianpay-api.tianshupay.xyz/api/v1/payment/init',
        'query_url' => 'https://xinglianpay-api.tianshupay.xyz/api/v1/payment/query',
    ],
    'payment_conf_alinpay' => [
        'key' => 'm0wqhjiq004r0mcaisv2dxhe76zii3p4',
        'pay_memberid'=>'240505774',
        'pay_notifyurl' => env('app.host').'/common/payNotify_alinpay',
        'pay_callbackurl' => env('common.callback_url').'/tradeSuccess',
        'payment_url' => 'http://alinpaytue.meisuobudamiya.com/Pay_Index.html',
        'query_url' => 'http://alinpaytue.meisuobudamiya.com/Pay_Trade_query.html',
    ],
    'payment_conf_yunsf' => [
        'key' => 'TN9FI1VRIKBTCPVW5Z3HSPUPY6ZVUABOFNZNW7AZHPBC1BUXQTJH6HEMFNNMNSI5CBT332AFBTJTTGQESTFQ0XWBY1QOOVT5EQJDJM29OZPRR8K81FU9LESES9SPP2SP',
        'pay_memberid'=>'880123110602',
        'pay_notifyurl' => env('app.host').'/common/payNotify_yunsf',
        'pay_callbackurl' => env('common.callback_url').'/tradeSuccess',
        'payment_url' => 'https://pay.yysf.app/api/payAPI/create',
        'query_url' => 'https://pay.yysf.app/api/payAPI/queryOrder',
    ],
    'payment_conf_huitong' => [
        'key' => 'h0ihb3jf28scz0ww9txrjr4jnnosahup',
        'pay_memberid'=>'250282191',
        'pay_notifyurl' => env('app.host').'/common/paynotify_huitong',
        'pay_callbackurl' => env('common.callback_url').'/tradeSuccess',
        'payment_url' => 'http://spay.huitong.boyuepay.com/Pay_Index.html',
        'query_url' => 'http://spay.huitong.boyuepay.com/Pay_Trade_query.html',
    ],
    'payment_conf_fengxin' => [
        'key' => 'ZO8XOKCLGRDKH3NYS9QEN08KAKCM1OVXADYWWACK5MF4QUQDDDPOQKUYVNMWSBMUGL8EU5NFAOSLGBEJUCXP8IPPJUKDVSQGOJ0PSQEPMD5XBSJNX1RBEYOGFN5BLXEO',
        'pay_memberid'=>'35006218570',
        'pay_notifyurl' => env('app.host').'/common/paynotifyfengxin',
        'pay_callbackurl' => env('common.callback_url').'/tradeSuccess',
        'payment_url' => 'https://pay.aupiu.com/api/payAPI/create',
        'query_url' => 'https://pay.aupiu.com/api/payAPI/queryOrder',
    ],
    'payment_conf_fengxiong' => [
        'key' => 'DIGVJOK4HW0W3ZKQKFSQHZJKR44P6A1E3WXHGF1NDFXRKRVGLWSQNCXKZVM1HBICWSJZKGJDB9UWPW6NYARKI3OZCKXAKNFCLTSTU1F18A3V6PUGUIU1QHFN3BVDEEOA',
        'pay_memberid'=>'20000696',
        'pay_notifyurl' => env('app.host').'/common/paynotifyfengxiong',
        'pay_callbackurl' => env('common.callback_url').'/tradeSuccess',
        'payment_url' => 'https://yhhb.ohsf.xyz/api/pay/create_order',
        'query_url' => 'https://yhhb.ohsf.xyz/api/pay/query_order',
    ],
    'payment_conf_xxpay' => [
        'key' => 'H6Q66SR8OCUAXROH3DCV4GCNMEWP5JBZUDHOFTLHTH75MNMYDCSQ7TOSZVZQD3SATHTWK4W2JBSJOTLM6XZSTTWTUKHTJTVJSBK8PYYKCSOIRS07FGI537NMW3MGPZBD',
        'pay_memberid'=>'20000003',
        'pay_notifyurl' => env('app.host').'/common/paynotify_xxpay',
        'pay_callbackurl' => env('common.callback_url').'/tradeSuccess',
        'payment_url' => 'http://103.45.64.81:56700/api/pay/create_order',
        'query_url' => 'http://103.45.64.81:56700/api/pay/query_order',
    ],
    'payment_conf_yiji' => [
        'key' => 'X8STMWR4O6LF1CPVU3',
        'pay_memberid'=>'10006',
        'pay_notifyurl' => env('app.host').'/common/paynotifyyiji',
        'pay_callbackurl' => env('common.callback_url').'/tradeSuccess',
        'payment_url' => 'http://zfzz.5fbao.com/Pay.html',
        'query_url' => 'http://zfzz.5fbao.com/Pay.html',
    ],
    'payment_conf_yiji1' => [
        'key' => '4J21OVHL8AI57GZE43',
        'pay_memberid'=>'10006',
        'pay_notifyurl' => env('app.host').'/common/paynotifyyiji1',
        'pay_callbackurl' => env('common.callback_url').'/tradeSuccess',
        'payment_url' => 'http://zfzz.5fbao.com/Pay.html',
        'query_url' => 'http://zfzz.5fbao.com/Pay.html',
    ],
    'payment_conf_jinhai' => [
        'key' => 'CHU6YTD5XJANJMP84LLLCEWB6OXOKHS1MCOQMUNNXIAWJEP1EZMMZXJPOTSATKPZTWWBIPWJUIJU8UN7B1SNH63GYLNWHWPXJBAZRPMDABH8DLAZJLHAMJLOU85SQWCM',
        'pay_memberid'=>'20000003',
        'pay_notifyurl' => env('app.host').'/common/paynotifyjinhai',
        'pay_callbackurl' => env('common.callback_url').'/tradeSuccess',
        'payment_url' => 'http://202.79.161.37:56700/api/pay/create_order',
        'query_url' => 'http://202.79.161.37:56700/api/pay/query_order',
    ],
    'payment_conf_maimaitong' => [
        'key' => 'SOEPBC7JO99PPMDRTMGOQKGT8VZ7Y4UYN5TGFYKEFPZHVLRNHBTLIDNS4T40LBXWUUOZBTTUWGIMALPJZMEUK2QA6QNJBJZ5E91DNTMGA6TD4XRMLIF6KWZ1O8WEVEGT',
        'pay_memberid'=>'20000018',
        'pay_notifyurl' => env('app.host').'/common/paynotifymaimaitong',
        'pay_callbackurl' => env('common.callback_url').'/tradeSuccess',
        'payment_url' => 'https://bm5c6u.mmtpay.net/api/pay/startOrder',
        'query_url' => 'https://bm5c6u.mmtpay.net/api/pay/query_order',
    ],
    'payment_conf_yangguang' => [
        'key' => 'SQ0F5ELU2RZEJB9BTB69KXPXTPF8IBOC246CWMUYSX4HX6LIUGOZNFJRWLD0EAB69OI4X7HLQ2J4FFB2ABWDSKPK6DJKCK9CQDHPIRG9SH3TGHUAT5QKQX5UIH0QP3PO',
        'pay_memberid'=>'20000021',
        'pay_notifyurl' => env('app.host').'/common/paynotify_yangguang',
        'pay_callbackurl' => env('common.callback_url').'/tradeSuccess',
        'payment_url' => 'http://202.79.161.95:56700/api/pay/create_order',
        'query_url' => 'http://202.79.161.95:56700/api/pay/query_order',
    ],
    'payment_conf_huiying' => [
        'key' => 'd160cc6e3fe31fda87af2e52112801fb',
        'pay_memberid'=>'56689',
        'pay_notifyurl' => env('app.host').'/common/paynotify_huiying',
        'pay_callbackurl' => env('common.callback_url').'/tradeSuccess',
        'payment_url' => 'http://w55879.lobopay.xyz/api/order',
        'query_url' => 'http://w55879.lobopay.xyz/api/query',
    ],
    'payment_conf_huifu' => [
        'key' => 'kys71M1oaW2eJYhKIvY1kJA',
        'pay_memberid'=>'1005',
        'pay_notifyurl' => env('app.host').'/common/paynotifyhuifu',
        'pay_callbackurl' => env('common.callback_url').'/tradeSuccess',
        'payment_url' => 'https://tsapi-huifu.tsakak.com/api/v1/payment/init',
        'query_url' => 'https://tsapi-huifu.tsakak.com/api/v1/payment/query',
    ],
    // 'payment_conf3' => [
    //     'key' => '9ypdnklv4u79vqt42n6ub9pnfb3e546c',
    //     'pay_memberid' => '220986355',
    //     'pay_notifyurl' => env('app.host').'/common/payNotify3',
    //     'pay_callbackurl' => env('common.callback_url').'/tradeSuccess',
    //     'payment_url' => 'http://tue.xinlongkeji.top/Pay_Index.html',
    //     'query_url' => 'http://tue.xinlongkeji.top/Pay_Trade_query.html',
    // ],

    // 被动收益
    'passive_income_days_conf' => [
        1 => 0.1,
        2 => 0.2,
        3 => 0.3,
        4 => 0.4,
        5 => 0.5,
        6 => 0.6,
        7 => 0.7,
        8 => 1.6,
        9 => 1.8,
        10 => 2,
        11 => 2.2,
        12 => 2.4,
        13 => 2.6,
        14 => 2.8,
        15 => 6,
        16 => 6.4,
        17 => 6.8,
        18 => 7.2,
        19 => 7.6,
        20 => 8,
        21 => 8.4,
        22 => 17.6,
        23 => 18.4,
        24 => 19.2,
        25 => 20,
        26 => 20.8,
        27 => 21.6,
        28 => 22.4,
        29 => 46.4,
        30 => 48,
        31 => 49.6,
        32 => 51.2,
        33 => 52.8,
        34 => 54.4,
        35 => 56,
        36 => 115.2,
        37 => 118.4,
        38 => 121.6,
        39 => 124.8,
        40 => 128,
        41 => 131.2,
        42 => 134.4,
        43 => 275.2,
        44 => 281.6,
        45 => 288,
        46 => 294.4,
        47 => 300.8,
        48 => 307.2,
        49 => 313.6,
        50 => 640,
        51 => 652.8,
        52 => 665.6,
        53 => 678.4,
        54 => 691.2,
        55 => 704,
        56 => 716.8,
        57 => 1459.2,
        58 => 1484.8,
        59 => 1510.4,
        60 => 1536,
        61 => 1561.6,
        62 => 1587.2,
        63 => 1612.8,
        64 => 3276.8,
        65 => 3328,
        66 => 3379.2,
        67 => 3430.4,
        68 => 3481.6,
        69 => 3532.8,
        70 => 3584,
        71 => 7270.4,
        72 => 7372.8,
        73 => 7475.2,
        74 => 7577.6,
        75 => 7680,
        76 => 7782.4,
        77 => 7884.8,
    ],
];
